name: pet_pal_dyary
description: "A new Flutter project."
publish_to: 'none' # Para evitar publicación accidental

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  intl: ^0.20.2
  image_picker: ^0.8.7+4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/